# 1. Setup Phase (Changed 'jdk21' to 'jdk')
[phases.setup]
nixPkgs = ["jdk", "maven", "nodejs"]

[phases.frontend]
cmds = ["cd client && npm install && CI=false npm run build"]

# 3. Copy React files to Java folder
[phases.copy_assets]
dependsOn = ["frontend"]
cmds = [
    "mkdir -p matessa/src/main/resources/static",
    "cp -r client/build/* matessa/src/main/resources/static/"
]

# 4. Build the Backend (Java)
[phases.build]
dependsOn = ["copy_assets"]
cmds = ["cd matessa && mvn clean package -DskipTests"]

# 5. Start the Server
[start]
cmd = "java -jar matessa/target/*.jar"