spring.application.name=matessa

spring.security.user.password=anas0101
spring.security.user.name=anasha
spring.app.jwtSecret=MySuperSecretKeyForMatessaProjectThatIsVeryLongAndSecure2025
spring.app.jwtExpirationMs=86400000
spring.ecom.jwtCookieName=jwtCookieEcom
#spring.datasource.url=jdbc:h2:mem:matessa_db
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
project.image=images/

#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.format_sql=true
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/ecommerce}\
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}\
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:@nas09303Anas}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Configuration
# 'update' will automatically create/modify tables based on your Java Entities
spring.jpa.hibernate.ddl-auto=update

# Show SQL queries in the console (Helpful for debugging)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Dialect (Optional in Spring Boot 3, but good to be explicit)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB



logging.level.org.springframework=DEBUG
logging.level.org.hibernate.sql=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.com.ecommerce.matessa=DEBUG
